name: CICD

on:
  push:
    branches: [deploy-to-ec2]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Change to project directory
        run: cd services/transportcore
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build project
        run: ./gradlew build
      - name: Login to docker
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t tacticalaxis/transportcore .
      - name: Publish to docker hub
        run: docker push tacticalaxis/transportcore:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker
        run: docker pull tacticalaxis/transportcore:latest
      - name: Delete old container if exists
        run: docker rm -f transportcore-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name transportcore-container tacticalaxis/transportcore